/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

#import "PSControlTableCell.h"

@interface PSSliderTableCell : PSControlTableCell {
    UIView * _disabledView;
}

- (BOOL)canReload;
- (id)controlValue;
- (id)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(id)indentifier specifier:(id)specifier;
- (void)layoutSubviews;
- (id)newControl;
- (void)prepareForReuse;
- (void)refreshCellContentsWithSpecifier:(id)arg1;
- (void)setCellEnabled:(BOOL)arg1;
- (void)setValue:(id)arg1;
- (id)titleLabel;

@end